name: Zip Files

on:
  push:


jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'cputhrottle@schnoog.eu'
      - uses: vimtor/action-zip@v1.2
        with:
          files: dist/ manifest.json
          dest: result.zip
