name: Release Package of Repository on Tag


on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Create Tagname
        run: echo "TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        
      - name: Echo current date
        run: echo $NOW # Gives "2022-12-11T01:42:20"
        
      - name: Set zip file variable
        run: echo "ZFN=CPUThrottleApplet-""$NOW"".zip" >> $GITHUB_ENV
        
      - name: Echo zip file name
        run: echo $ZFN # Gives "2022-12-11T01:42:20"
        

########################## CHECKOUT        
      - name: Checkout Repository
        uses: actions/checkout@v4
########################## MKDIR AND COPY
      - name: Create Directory and Move Files
        run: |
          mkdir cputhrottle@schnoog.eu
          cp ./*.sh ./cputhrottle@schnoog.eu/
          cp ./*.js ./cputhrottle@schnoog.eu/
          cp ./*.json ./cputhrottle@schnoog.eu/
          cp ./*.md ./cputhrottle@schnoog.eu/
          cp ./*.png ./cputhrottle@schnoog.eu/
          cp ./*.jpg ./cputhrottle@schnoog.eu/
########################## ZIP
      - name: Zip the Directory
        run: |
          zip -r ${{ env.ZFN }} cputhrottle@schnoog.eu

########################## CREATE RELEASE
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:  ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
########################## UPLOAD ASSETS
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ZFN }}
          asset_name: ${{ env.ZFN }}
          asset_content_type: application/zip